<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>val</string>
		<string>valtree</string>
		<string>vt</string>
	</array>
	<key>name</key>
	<string>ValTree</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.valtree</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#.+)</string>
			<key>name</key>
			<string>comment.line.number-sign.valtree</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.valtree</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.valtree</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.valtree</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^\s]+)\s+(\d+(\.\d+)?)</string>
			<key>name</key>
			<string>keyword.source.valtree</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.valtree</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.valtree</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([^\s]+)(.*)</string>
			<key>name</key>
			<string>keyword.source.valtree</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.valtree</string>
	<key>uuid</key>
	<string>5d75ae2c-0f2e-4bb3-85d4-e64421333a8f</string>
</dict>
</plist>
